name: Nuclei - Vulnerability Scan

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: www.kiyiemniyeti.gov.tr

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v3  # Updated version
        with:
          name: nuclei.log
          path: nuclei.log
